[default]
key = "value"
databases = { default = { db_url = "postgresql+psycopg://postgres:postgres@127.0.0.1:5432/" } }
pg_url = "postgresql+psycopg://postgres:postgres@127.0.0.1:5432/"
pg_a_url = "postgresql+psycopg_async://postgres:postgres@127.0.0.1:5432/"

[test]
key = "abc"
databases.default.url = "postgresql+psycopg_async://postgres:postgres@127.0.0.1:5432/"
