name: Python PDM Project CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true  # Enable caching for faster builds
        version: "latest"  # Specify the version of uv to install
      # You are now able to use PDM in your workflow
    - name: Install dependencies
      run: uv sync
    - name: run tests and coverage report
      run: |
        uv run cov
        uv run check_format
        uv run badge